### ISSUE TITLE
iSponsorblock not auto skipping sponsored content on videos

### ISSUE THREAD

**Issue by sauron3256** [TherionRO/YouTubeiVanced#25] opened 2024-02-20 07:18 UTC
YouTube iVanced version 19.06.2
Installed on iPhone 14, iOS 17.3.1 via AppDB

While Sponsorblock is active and marks the sponsored content on any video, it does not auto skip it, instead it plays normally, like Sponsorblock is disabled. To solve the problem I had to downgrade to v19.05.5

Steps to reproduce the issue

Sideload YouTube iVanced v19.06.2
Make sure that Sponsorblock is active and on autoskip on sponsored content.
Play any video that has sponsored content.

**Comment by TherionRO** [comment] 2024-02-20 08:25
Hey! I also tested it on my device and got the same results,most likely the isponsorblock tweak is broken with the latest yt version. Im gonna try to look into it to see whats the cause of it. Thank you for pointing out!

**Comment by TherionRO** [comment] 2024-02-27 14:58
It should be fixed with iVanced 19.08.2,from my testings iSponsorblock works as it should!

**Closed by TherionRO** 2024-02-27 14:58 UTC
