### ISSUE TITLE
Shorts crashes 

### ISSUE THREAD

**Issue by Haze040** [TherionRO/YouTubeiVanced#6] opened 2023-01-30 19:43 UTC
YouTube Shorts crashes instant

**Comment by Haze040** [comment] 2023-01-30 21:38
Thank you

**Comment by DiasporaLive** [comment] 2023-01-30 21:48
Hi.issue caused by some broken dependencies from my testings
@TherionRO  will look into it.

**Comment by TherionRO** [comment] 2023-03-01 23:34
Shorts crash is now fixed.

**Closed by TherionRO** 2023-03-01 23:34 UTC
Labels: bug
